BINDIR='/usr/local/bin'
CC='gcc'
CFLAGS='-O2 -g'
COUNTSUFFIX='.cnt'
DEFHASH='english.hash'
DEFLANG='english.aff'
ELISPDIR='/usr/local/lib/emacs/site-lisp'
EMACS='emacs'
HASHSUFFIX='.hash'
INSTALL='cp'
LANGUAGES='{american,MASTERDICTS=american.med+,HASHFILES=americanmed+.hash,EXTRADICT=words}'
LIBDIR='.'
LIBES=''
LINT='lint'
LINTFLAGS=''
MAKE_SORTTMP='-T ${TMPDIR-/tmp}'
MAN1DIR='/usr/local/man/man1'
MAN1EXT='.1'
MAN4DIR='/usr/local/man/man4'
MAN4EXT='.4'
MASTERHASH='americanmed+.hash'
MSGLANG='english'
REGLIB=''
STATSUFFIX='.stat'
TERMLIB=''
TEXINFODIR='/usr/local/info'
YACC='yacc'
case "$MAKE_SORTTMP" in "")  SORTTMP="-e /!!SORTTMP!!/s/=.*$/=/";; *) SORTTMP=;; esac
