#!/bin/sh
#
# $Id: ishar,v 1.5 1994/01/25 07:11:38 geoff Exp $
#
# Copyright 1993, Geoff Kuenning, Granada Hills, CA
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All modifications to the source code must be clearly marked as
#    such.  Binary redistributions based on modified source code
#    must be clearly marked as modified versions in the documentation
#    and/or other materials provided with the distribution.
# 4. All advertising materials mentioning features or use of this software
#    must display the following acknowledgment:
#      This product includes software developed by Geoff Kuenning and
#      other unpaid contributors.
# 5. The name of Geoff Kuenning may not be used to endorse or promote
#    products derived from this software without specific prior
#    written permission.
#
# THIS SOFTWARE IS PROVIDED BY GEOFF KUENNING AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL GEOFF KUENNING OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# Simple shar script, suitable for packing up ispell and not a lot else.
#
# Usage:
#
#	shar [-p<prefix>] files
#
# The output format is stolen from Gary Perlman's shar program.
#
# $Log: ishar,v $
# Revision 1.5  1994/01/25  07:11:38  geoff
# Get rid of all old RCS log lines in preparation for the 3.1 release.
#
#
USAGE='Usage:  ishar [-p<prefix>] files'
prefix=
while [ $# -gt 0 ]
do
    case "$1" in
	-p*)
	    prefix=`expr "$1" : '-p\(.*\)'`
	    shift
	    ;;
	--)
	    shift
	    break
	    ;;
	-*)
	    echo "$USAGE" 1>&2
	    exit 1
	    ;;
	*)
	    break
    esac
done

#
# Start with the standard shar header
#
cat << 'End_Header'
#!/bin/sh
# This is a shell archive, meaning:
# 1. Remove everything above the #!/bin/sh line.
# 2. Save the resulting text in a file.
# 3. Execute the file with /bin/sh (not csh) to create the files:
End_Header
for file
do
    echo "#	$file"
done
echo '# This archive created:' `date`
echo 'PATH=/bin:$PATH; export PATH'

#
# Do files.  Note that we assume relative pathnames.  I don't consider
# this a bug.
#
nl='
'
for file
do
    echo echo shar: extracting '"'"'$file'"'"'
    case "$file" in
	*/*)
	    basedir=
	    sep=
	    for dir in `echo $file | sed 's;/[^/]*$;;' | tr / "$nl"`
	    do
		basedir=$basedir$sep$dir
		echo "[ -d $basedir ]  ||  mkdir $basedir"
		sep=/
	    done
	    ;;
    esac
    case "X$prefix" in
	X)
	    echo "cat << 'SHAR_EOF' > '$file'"
	    cat "$file"
	    ;;
	*)
	    echo "sed 's/^$prefix//' << 'SHAR_EOF' > '$file'"
	    sed "s/^/${prefix}/" "$file"
	    ;;
    esac
    echo SHAR_EOF
    if [ -x "$file" ]
    then
	echo chmod +x "'$file'"
    fi
done

#
# Finish off
#
echo '#	End of shell archive'
echo exit 0
